version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: ./entrypoints/api/Dockerfile
    ports:
      - "${LOL_STATS_CARD_API_PORT:-3000}:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
    volumes:
      - ./.storage:/app/.storage
    depends_on:
      - redis
    restart: on-failure

  caddy-api:
    image: caddy:2-alpine
    ports:
      - "${LOL_STATS_CARD_CADDY_API_HTTP_PORT:-8080}:80"
      - "${LOL_STATS_CARD_CADDY_API_HTTPS_PORT:-8443}:443"
    volumes:
      - ./entrypoints/api/Caddyfile:/etc/caddy/Caddyfile
      - caddy_api_data:/data
      - caddy_api_config:/config
    depends_on:
      - api
    restart: on-failure

  generator-queue:
    build:
      context: .
      dockerfile: ./entrypoints/generator-queue/Dockerfile
    environment:
      RIOT_API_KEY: ${RIOT_API_KEY}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
    volumes:
      - ./.storage:/app/.storage
    depends_on:
      - redis
    restart: on-failure

  webapp:
    build:
      context: .
      dockerfile: ./entrypoints/webapp/Dockerfile
    ports:
      - "${LOL_STATS_CARD_WEBAPP_HTTP_PORT:-80}:80"
      - "${LOL_STATS_CARD_WEBAPP_HTTPS_PORT:-443}:443"
    environment:
      VITE_API_URL: ${API_URL:-http://api.hypo-stats-lol2.orb.local/}
    volumes:
      - ./entrypoints/webapp/Caddyfile:/etc/caddy/Caddyfile # Added Caddyfile volume for webapp
      - caddy_webapp_data:/data
      - caddy_webapp_config:/config
    restart: on-failure

  redis:
    image: redis:alpine
    ports:
      - "${LOL_STATS_CARD_REDIS_EXT_PORT:-6379}:6379"
    restart: on-failure

volumes:
  caddy_api_data:
  caddy_api_config:
  caddy_webapp_data:
  caddy_webapp_config:
